MaVangMvc/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaVangDatabase.Data;
using MaVangMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using MaVangModel;
namespace MaVangMvc.Controllers
{
    public class OrderController : Controller
    {
        private readonly MaVangDbContext _context;
        public IActionResult Index()
        {
            return View();
        }

        public const string CARTKEY = "cart";

        public List<CartModel> GetCartItems()
        {
            var session = HttpContext.Session;
            string jsoncart = session.GetString(CARTKEY);
            if (jsoncart != null)
            {
                return JsonConvert.DeserializeObject<List<CartModel>>(jsoncart);
            }
            return new List<CartModel>();
        }

        public async Task<IActionResult> Checkout()
        {
            return View(GetCartItems());
        }
        
        [HttpPost]
        public async Task<IActionResult> CreateOrder(OrderCreateModel model)
        {
            if (ModelState.IsValid)
            {
                t_order order = new t_order
                {
                    CustomerName = model.Name,
                    Phone = model.Phone,
                    Address = model.Address,
                    Status = 0
                };
                _context.Add(order);
                await _context.SaveChangesAsync();
            }
            return View();
        }
    }
}

MaVangMvc/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaVangDatabase.Data;
using MaVangModel;
using MaVangMvc.Models;
using MaVangUtility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MaVangMvc.Controllers
{
    public class ProductController : Controller
    {
        private readonly MaVangDbContext _context;
        public const string CARTKEY = "cart";

        public List<CartModel> GetCartItems()
        {
            var session = HttpContext.Session;
            string jsoncart = session.GetString(CARTKEY);
            if (jsoncart != null)
            {
                return JsonConvert.DeserializeObject<List<CartModel>>(jsoncart);
            }
            return new List<CartModel>();
        }

        public void ClearCart()
        {
            var session = HttpContext.Session;
            session.Remove(CARTKEY);
        }

        public void SaveCartSession(List<CartModel> ls)
        {
            var session = HttpContext.Session;
            string jsonCart = JsonConvert.SerializeObject(ls);
            session.SetString(CARTKEY, jsonCart);
        }

        [Route("addcart/{productid:int}", Name = "addcart")]
        public IActionResult AddToCart([FromRoute] int ProductID)
        {
            var product = from p in _context.m_product
                          where p.ID == ProductID
                          select new ProductBaseModel
                          {
                              ProductID = p.ID,
                              Price = p.ProductPrice,
                              ProductName = p.ProductName,
                              ImgThumbnail = p.Thumbnail
                          };
                            
            if(product == null)
            {
                return NotFound("Khong tim thay san pham");
            }

            var cart = GetCartItems();
            var cartItem = cart.Find(p => p.Product.ProductID == ProductID);
            if(cartItem != null)
            {
                cartItem.Quantity++;
            }
            else
            {
                cart.Add(new CartModel() { Quantity = 1, Product = product.FirstOrDefault() });
            }
            SaveCartSession(cart);

            return RedirectToAction(nameof(Cart));
            //return Redirect(HttpContext.Request.Headers["Referer"]);
        }

        [Route("/cart", Name = "cart")]
        public IActionResult Cart()
        {
            return View(GetCartItems());
        }


        public ProductController(MaVangDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ProductListByCategory(int CategoryID, int? pageNumber)
        {
            var lstModel = from p in _context.m_product
                       where p.CategoryRefID.Equals(CategoryID)
                       select new ProductListModel
                       {
                           ProductName = p.ProductName,
                           ProductPrice = p.ProductPrice,
                           ImgThumbnail = p.Thumbnail,
                           ProductID = p.ID
                       };

            int pageSize = 12;

            return View(await PaginatedList<ProductListModel>.CreateAsync(lstModel.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> ProductDetail(int ProductID)
        {
            var model = from p in _context.m_product
                    join c in _context.m_category on p.CategoryRefID equals c.ID
                    where p.ID.Equals(ProductID) && p.DelFlg.Equals(false)
                    select new ProductDetailModel
                    {
                        ProductID = p.ID,
                        Category = c.CategoryName,
                        Price = p.ProductPrice,
                        Images = p.ProductImages,
                        ProductName = p.ProductName,
                        Description = p.Description
                    };
            return View(await model.FirstOrDefaultAsync());
        }

    }
}

MaVangMvc/Views/Product/Cart.cshtml
@model List<CartModel>
@{
}
<!--breadcrumbs area start-->
<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <h3>Giỏ Hàng</h3>
                    <ul>
                        <li><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                        <li>Thanh Toán</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--breadcrumbs area end-->
<!--shopping cart area start -->
<div class="shopping_cart_area mt-100">
    <div class="container">
        <form action="#">
            <div class="row">
                <div class="col-12">
                    <div class="table_desc">
                        <div class="cart_page table-responsive">
                            <table>
                                <thead>
                                    <tr>
                                        <th class="product_remove">Xóa</th>
                                        <th class="product_thumb">Ảnh Sản phẩm</th>
                                        <th class="product_name">Sản phẩm</th>
                                        <th class="product-price">Giá</th>
                                        <th class="product_quantity">Số lượng</th>
                                        <th class="product_total">Thành tiền</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="product_remove"><a href="#"><i class="fa fa-trash-o"></i></a></td>
                                            <td class="product_thumb"><a href="#"><img src="~/img/product/@item.Product.ImgThumbnail" alt=""></a></td>
                                            <td class="product_name"><a href="#">@item.Product.ProductName</a></td>
                                            <td class="product-price">@item.Product.Price.ToString("n0")</td>
                                            <td class="product_quantity"><label>Số lượng</label> @item.Quantity</td>
                                            <td class="product_total">@{ var total = item.Product.Price * item.Quantity;} @total.ToString("n0") VND</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="cart_submit">
                            <button type="submit">Cập nhập giỏ hàng</button>
                        </div>
                    </div>
                </div> 
            </div>
            <!--coupon code area start-->
            <div class="coupon_area">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="coupon_code right">
                            <h3>Tổng hóa đơn</h3>
                            <div class="coupon_inner">
                                <div class="cart_subtotal">
                                    <p>Tổng tièn</p>
                                    <p class="cart_amount">£215.00</p>
                                </div>
                                <div class="checkout_btn">
                                    <a asp-controller="Order" asp-action="Checkout">Đặt hàng</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--coupon code area end-->
        </form>
    </div>
</div>
<!--shopping cart area end -->

MaVangMvc/Views/Product/ProductDetail.cshtml
@model MaVangModel.ProductDetailModel
@{
}
<!--breadcrumbs area start-->
<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                        <li>Chi tiết sản phẩm</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--breadcrumbs area end-->
<!--product details start-->
<div class="product_details mt-100 mb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="product-details-tab">
                    <div id="img-1" class="zoomWrapper single-zoom">
                        <a href="#">
                            <img id="zoom1" src="~/img/product/Artboard_2_copy_2.jpg" data-zoom-image="~/img/product/Artboard_2_copy_2.jpg" alt="big-1">
                        </a>
                    </div>
                    <div class="single-zoom-thumb">
                        <ul class="s-tab-zoom owl-carousel single-product-active" id="gallery_01">
                            <li>
                                <a href="#" class="elevatezoom-gallery active" data-update="" data-image="~/img/product/Artboard_2_copy_2" data-zoom-image="~/img/product/Artboard_2_copy_2">
                                    <img src="~/img/product/Artboard_2_copy_2.jpg" alt="zo-th-1" />
                                </a>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="product_d_right">
                    <form action="#">

                        <h1><a href="#">@Model.ProductName</a></h1>
                        <div class="price_box">
                            <span class="current_price">@Model.Price.ToString("n0") VND</span>

                        </div>
                        <div class="product_variant quantity">
                            <label>quantity</label>
                            <input min="1" max="100" value="1" type="number">
                            <a class="button" asp-route="addcart" asp-route-productid="@Model.ProductID" style="margin-left:5px">Thêm vào giỏ hàng</a>
                        </div>
                        <div class="product_meta">
                            <span>Loại: <a href="#">@Model.Category</a></span>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!--product details end-->
<!--product info start-->
<div class="product_d_info mb-90">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="product_d_inner">
                    <div class="product_info_button">
                        <ul class="nav" role="tablist">
                            <li>
                                <a class="active" data-toggle="tab" href="#info" role="tab" aria-controls="info" aria-selected="false">Miêu tả sản phẩm</a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="info" role="tabpanel">
                            <div class="product_info_content">
                                @Model.Description
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--product info end-->

MaVangMvc/Views/Product/ProductListByCategory.cshtml
@model MaVangUtility.PaginatedList<MaVangModel.ProductListModel>
@{
}
<!--breadcrumbs area start-->
<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <h3>Cửa hàng</h3>
                    <ul>
                        <li><a href="index.html">Trang chủ</a></li>
                        <li>shop fullwidth</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--breadcrumbs area end-->
<!--shop  area start-->
<div class="shop_area shop_fullwidth mt-100 mb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!--shop wrapper start-->
                <!--shop toolbar start-->
                <div class="shop_toolbar_wrapper">
                    <div class="shop_toolbar_btn">

                        <button data-role="grid_3" type="button" class=" btn-grid-3" data-toggle="tooltip" title="3"></button>

                        <button data-role="grid_4" type="button" class="active btn-grid-4" data-toggle="tooltip" title="4"></button>

                        <button data-role="grid_list" type="button" class="btn-list" data-toggle="tooltip" title="List"></button>
                    </div>
                    @*<div class=" niceselect_option">
                <form class="select_option" action="#">
                    <select name="orderby" id="short">
                        <option selected value="1">Sort by average rating</option>
                        <option value="2">Sort by popularity</option>
                        <option value="3">Sort by newness</option>
                        <option value="4">Sort by price: low to high</option>
                        <option value="5">Sort by price: high to low</option>
                        <option value="6">Product Name: Z</option>
                    </select>
                </form>
            </div>*@
                    <div class="page_amount">
                        <p>Có @Model.Count sản phẩm </p>
                    </div>
                </div>
                <!--shop toolbar end-->
                <div class="row shop_wrapper grid_4">
                    @foreach (var item in Model)
                    {
                        <div class="col-lg-3 col-md-4 col-12 ">
                            <article class="single_product">
                                <figure>
                                    <div class="product_thumb">
                                        <a class="primary_img" asp-action="ProductDetail" asp-controller="Product" asp-route-ProductID="@item.ProductID" ><img src="~/img/product/@item.ImgThumbnail" alt=""></a>
                                        <div class="action_links">
                                            <ul>
                                                <li class="add_to_cart"><a href="cart.html" title="Add to cart"><i class="icon-shopping-bag"></i></a></li>
                                                <li class="quick_button"><a href="#" data-toggle="modal" data-target="#modal_box" title="quick view"> <i class="icon-eye"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="action_links list_action">
                                            <ul>
                                                <li class="quick_button"><a href="#" data-toggle="modal" data-target="#modal_box" title="quick view"> <i class="icon-eye"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="product_content grid_content">
                                        <div class="product_price_rating">
                                            <h4 class="product_name"><a asp-action="ProductDetail" asp-controller="Product" asp-route-ProductID="@item.ProductID" >@item.ProductName</a></h4>
                                            <div class="price_box">
                                                <span class="current_price">@item.ProductPrice.ToString("n0")VND</span>
                                            </div>
                                        </div>
                                    </div>
                                </figure>
                            </article>
                        </div>
                    }
                </div>
                @if (Model.Count() > 12)
                {
                    <div class="shop_toolbar t_bottom">
                        <div class="pagination">
                            <ul>
                                @{
                                    for (var i = 1; i <= Model.TotalPages; i++)
                                    {
                                        <li class="current">1</li>
                                        <a asp-action="Index" asp-route-pageNumber="@i" class=" @(i == Model.PageIndex ? "current" : "")">@i</a>
                                    }
                                }
                            </ul>
                        </div>
                    </div>
                }
                <!--shop toolbar end-->
                <!--shop wrapper end-->
            </div>
        </div>
    </div>
</div>
<!--shop  area end-->