MaVangMvc/Views/Shared/ViewComponents/BasketViewComponent.cs
using MaVangMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MaVangMvc.Views.Shared.ViewComponents
{
    public class BasketViewComponent : ViewComponent
    {
        public const string CARTKEY = "cart";
            
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var session = HttpContext.Session;
            var jsonCart  = session.GetString(CARTKEY);
            if (jsonCart != null)
            {
                var cartItem = JsonConvert.DeserializeObject<List<CartModel>>(jsonCart);
                var TotalOfQuatity = 0;
                for (int i = 0; i < cartItem.Count; i++)
                {
                    TotalOfQuatity += cartItem[i].Quantity;
                }
                ViewData["CartItemCount"] = TotalOfQuatity;
            }
            return View();
        }
    }
}

MaVangMvc/Views/Shared/ViewComponents/MenuCategoryViewComponent.cs
using MaVangDatabase.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaVangMvc.Models;
using Microsoft.EntityFrameworkCore;

namespace MaVangMvc.Views.Shared.ViewComponents
{
    public class MenuCategoryViewComponent : ViewComponent
    {
        private readonly MaVangDbContext _context;
        public MenuCategoryViewComponent(MaVangDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var item = await GetItemsAsync();
            return View(item);
        }
        
        private Task<List<MenuCategoryModel>> GetItemsAsync()
        {
            return  _context.m_category.Select(c => new MenuCategoryModel { CategoryID = c.ID, CategoryName = c.CategoryName }).ToListAsync();
        }
       
    }
}

MaVangMvc/Views/Shared/ViewComponents/MiniCartViewComponent.cs
using MaVangMvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MaVangMvc.Views.Shared.ViewComponents
{
    public class MiniCartViewComponent : ViewComponent
    {
        public const string CARTKEY = "cart";
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var session = HttpContext.Session;
            var jsonCart = session.GetString(CARTKEY);
            if (jsonCart != null)
            {
                var model = JsonConvert.DeserializeObject<List<CartModel>>(jsonCart);
                decimal totalPrice = 0;
                foreach (var item in model)
                {
                    totalPrice = item.Quantity * item.Product.Price + totalPrice;
                }
                ViewData["TotalPrice"] = totalPrice.ToString("n0");
                return View(model);
            }
            return View(new List<CartModel>());
        }
    }
}

MaVangMvc/Views/Shared/ViewComponents/ProdListHomeViewComponent.cs
using MaVangDatabase.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaVangModel;

namespace MaVangMvc.Views.Shared.ViewComponents
{
    public class ProdListHomeViewComponent : ViewComponent
    {
        private readonly MaVangDbContext _context;
        public ProdListHomeViewComponent(MaVangDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ProductListHomePageModel model = new ProductListHomePageModel();
            model.noithatList = (from p in _context.m_product
                                 where p.CategoryRefID.Equals(1) && p.DelFlg.Equals(false)
                                 select new ProductListModel
                                 {
                                     ProductName = p.ProductName,
                                     ProductPrice = p.ProductPrice,
                                     ImgThumbnail = p.Thumbnail,
                                     ProductID = p.ID
                                 }).ToList();

            model.phukienList = (from p in _context.m_product
                                 where p.CategoryRefID.Equals(2) && p.DelFlg.Equals(false)
                                 select new ProductListModel
                                 {
                                     ProductName = p.ProductName,
                                     ProductPrice = p.ProductPrice,
                                     ImgThumbnail = p.Thumbnail,
                                     ProductID = p.ID
                                 }).ToList();

            model.ortherList = (from p in _context.m_product
                                where p.CategoryRefID != 1 && p.CategoryRefID != 2 && p.DelFlg.Equals(false)
                                 select new ProductListModel
                                 {
                                     ProductName = p.ProductName,
                                     ProductPrice = p.ProductPrice,
                                     ImgThumbnail = p.Thumbnail,
                                     ProductID = p.ID
                                 }).ToList();

            return View(model);
        }
    }
}

MaVangMvc/Views/Shared/_Header.cshtml
<div class="header_middle">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-3 col-4">
                <div class="logo">
                    <a href="index.html"><img src="~/img/logo/mavang24kluxury.png" /></a>

                </div>
            </div>
            <div class="col-lg-9 col-md-6 col-6">
                <div class="header_right_info">
                    <div class="search_container">
                        <form action="#">
                            <div class="hover_category">
                                <select class="select_option" name="select" id="categori1">
                                    <option selected value="1">All Categories</option>
                                    <option value="2">Accessories</option>
                                    <option value="3">Accessories & More</option>
                                    <option value="4">Butters & Eggs</option>
                                    <option value="5">Camera & Video </option>
                                    <option value="6">Mornitors</option>
                                    <option value="7">Tablets</option>
                                    <option value="8">Laptops</option>
                                    <option value="9">Handbags</option>
                                    <option value="10">Headphone & Speaker</option>
                                    <option value="11">Herbs & botanicals</option>
                                    <option value="12">Vegetables</option>
                                    <option value="13">Shop</option>
                                    <option value="14">Laptops & Desktops</option>
                                    <option value="15">Watchs</option>
                                    <option value="16">Electronic</option>
                                </select>
                            </div>
                            <div class="search_box">
                                <input placeholder="Search product..." type="text">
                                <button type="submit"><i class="icon-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="header_account_area">
                        <div class="header_account-list  mini_cart_wrapper">
                            @await Component.InvokeAsync("Basket")
                            <!--mini cart-->
                            @await Component.InvokeAsync("MiniCart")
                            <!--mini cart end-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MaVangMvc/Views/Shared/_Menubar.cshtml
@model IEnumerable<MenuCategoryModel>
@{
}
<div class="main_menu menu_position">
    <nav>
        <ul>
            <li>
                <a class="active" href="index.html">Trang Chủ<i class="fa fa-angle-down"></i></a>
            </li>
            <li class="mega_items">
                <a href="shop.html">shop<i class="fa fa-angle-down"></i></a>
                <div class="mega_menu">
                    <ul class="mega_menu_inner">
                        <li>
                            <a href="#">Sản phẩm</a>
                            <ul>
                                @*@foreach(var item in Model)
                                {
                                    <li><a href="shop-fullwidth.html">@item.CategoryName</a></li>
                                }*@
                            </ul>
                        </li>
                    </ul>
                </div>
            </li>
            <li><a href="contact.html"> Contact Us</a></li>
        </ul>
    </nav>
</div>