MaVangAdmin/Models/ErrorViewModel.cs
using System;

namespace MaVangAdmin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MaVangAdmin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaVangDatabase.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace MaVangAdmin.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ILogger<CategoryController> _logger;
        private readonly MaVangDbContext _context;

        public CategoryController(ILogger<CategoryController> logger, MaVangDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult CategoryList(string searchString, string currentFilter, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFillter"] = searchString;
            var category = from m in _context.m_category
                           select m;
            
            return View(category);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public  IActionResult Create(m_category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                _context.SaveChanges();
                _logger.LogInformation("Create sucess category ID: " + category.ID);
                return RedirectToAction("CategoryList");
            }
            return View();
            
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                m_category categoryDelete = new m_category() { ID = id };
                _context.Entry(categoryDelete).State = EntityState.Deleted;

                await _context.SaveChangesAsync();
                _logger.LogInformation("Remove sucess category ID: " + categoryDelete.ID);
            }
            return RedirectToAction("CategoryList");
        }
    }
}

MaVangAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MaVangAdmin.Models;
using Microsoft.AspNetCore.Authorization;

namespace MaVangAdmin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MaVangAdmin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaVangDatabase.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MaVangUtility;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using MaVangModel;
using MaVangAdmin.Utility;
using Microsoft.AspNetCore.Hosting;

namespace MaVangAdmin.Controllers
{
    public class ProductController : Controller
    {
        private readonly MaVangDbContext _context;
        private readonly ILogger<ProductController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(MaVangDbContext context, ILogger<ProductController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> ProductList(string searchString, string currentFilter, int? pageNumber)
        {
            try
            {
                if(searchString != null)
                {
                    pageNumber = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewData["CurrentFilter"] = searchString;
                var product = from p in _context.m_product
                              join c in _context.m_category on p.CategoryRefID equals c.ID
                              select p;
                if (!String.IsNullOrEmpty(searchString))
                {
                    product = product.Where(p => p.ProductName.Contains(searchString));
                }
                
                int pageSize = 10;

                return View(await PaginatedList<m_product>.CreateAsync(product.AsNoTracking(), pageNumber ?? 1, pageSize));
            }catch(Exception ex)
            {
                _logger.LogError(ex.Message);
                return View();
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            ProductCreateModel obj = new ProductCreateModel();
            obj.Categories =  _context.m_category.Where(m => m.DelFlg == false).AsEnumerable();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateModel model)
        {

            if (ModelState.IsValid)
            {
                string uniqueThumbnailName = UploadedFile.UploadedImage(_webHostEnvironment, model.Thumbnail);
                string productImageName = "";
                for (int i = 0; i < model.ProductImage.Count; i++)
                {
                    productImageName += UploadedFile.UploadedImage(_webHostEnvironment, model.ProductImage[i]) + ";" ;
                }
                m_product prod = new m_product
                {
                    ProductName = model.ProductName,
                    ProductPrice  = model.ProductPrice,
                    ProductImages = productImageName,
                    CategoryRefID = model.ProductCategory,
                    DelFlg = false,
                    Thumbnail = uniqueThumbnailName,
                    Description = model.Description
                };

                _context.Add(prod);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ProductList));
            }
            model.Categories = _context.m_category.Where(m => m.DelFlg == false).AsEnumerable();
            return View(model);
        }
    }
}

MaVangAdmin/Views/Category/CategoryList.cshtml
@model IEnumerable<MaVangDatabase.Data.m_category>
@{
}
<div class="page-title">
    <div class="title_left">
        <h3>Quản lý loại sản phẩm</h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group" style="padding-top:10px;float:right">
                <a href="@Url.Action("Create","Category")" class="btn btn-round btn-success" style="padding-left:20px;padding-right:20px"><i class="fa fa-plus" aria-hidden="true"></i> Tạo mới</a>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_content">

            <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                    <thead>
                        <tr class="headings">
                            <th class="column-title">Id </th>
                            <th class="column-title">Tên loại sản phẩm </th>
                            <th class="column-title">Trạng thái </th>
                            <th class="column-title"> </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr class="even pointer">
                            <td>@Html.DisplayFor(modelItem => item.ID)</td>
                            <td>@Html.DisplayFor(modelItem => item.CategoryName)</td>
                            <td>
                                @{
                                    if (item.DelFlg != true)
                                    {
                                        <span>Active</span>
                                    }
                                    else
                                    {
                                        <span>Deleted</span>
                                    }
                                }
                            </td>
                            <td>@Html.ActionLink("Xóa","Delete", new { id = item.ID}, new { onclick="return confirm('Bạn có chắc chắn muốn xóa danh mục sản phẩm" + item.CategoryName + "?')" })</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@section scripts{ 
    <script type="text/javascript">
        $(function () {
            $("a.delete-link").click(function () {

            })
        })
    </script>
}

MaVangAdmin/Views/Category/Create.cshtml
@model MaVangDatabase.Data.m_category;
@{
}
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Thêm mới loại sản phẩm</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br>
            @using (Html.BeginForm("Create", "Category", FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
            {

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                        Tên danh mục sản phẩm <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(m => m.CategoryName, "", new { @class = "form-control col-md-7 col-xs-12", @required = "required" })
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <a href="@Url.Action("CategoryList","Category")" class="btn btn-primary"> Cancel</a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MaVangAdmin/Views/Login/LoginAccount.cshtml
@model MaVangAdmin.Controllers.Login.InputModel
@{
    Layout = "~/Views/Shared/_LoginPage.cshtml";
}
<div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
        <div class="animate form login_form">
            <section class="login_content">
                @using (Html.BeginForm("LoginAccount", "Login", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <h1>Login Form</h1>
                    <div>
                        @Html.TextBoxFor(m=> m.Email, "", new {@class="form-control", @placeholder= "Username"})
                    </div>
                    <div>
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "PassWord" })
                    </div>
                    <div>
                        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                    </div>

                    <div class="clearfix"></div>

                    <div class="separator">

                        <div class="clearfix"></div>
                        <br />

                        <div>
                            <h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
                            <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
                        </div>
                    </div>
                }
            </section>
        </div>

    </div>
</div>

MaVangAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico" />

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
    <!-- bootstrap-daterangepicker -->
    <link href="/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/build/css/custom.min.css" rel="stylesheet">
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                          <a href="@Url.Action("Index","Home")" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="~/images/img.jpg" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>John Doe</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3></h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-leaf"></i> Quản lý Sản phẩm <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Quản lý loại sản phẩm", "CategoryList", "Category")</li>
                                        <li>@Html.ActionLink("Quản lý sản phẩm", "ProductList", "Product")</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="~/images/img.jpg" alt="">John Doe
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"> Profile</a></li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="badge bg-red pull-right">50%</span>
                                            <span>Settings</span>
                                        </a>
                                    </li>
                                    <li><a href="javascript:;">Help</a></li>
                                    <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>

                            <li role="presentation" class="dropdown">
                                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="badge bg-green">6</span>
                                </a>
                                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="text-center">
                                            <a>
                                                <strong>See All Alerts</strong>
                                                <i class="fa fa-angle-right"></i>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">

                @RenderBody()

                <!-- /page content -->
            </div>
    </div>

    <!-- jQuery -->
    <script src="/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="/vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="/vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="/vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="/vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="/vendors/Flot/jquery.flot.js"></script>
    <script src="/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="/vendors/Flot/jquery.flot.time.js"></script>
    <script src="/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="/vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="/vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="/vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="/vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="/vendors/moment/min/moment.min.js"></script>
    <script src="/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/build/js/custom.min.js"></script>
    @RenderSection("scripts", required:false)
        
</body>
</html>

MaVangAdmin/Views/Shared/_LoginPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/vendors/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/build/css/custom.min.css" rel="stylesheet">
</head>

<body class="login">
    @RenderBody()
</body>
</html>